import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="px-4 grid min-h-screen grid-rows-[auto,1fr,auto] container m-auto ">
        <header className="font-bold leading-[60xp] ">Kin+Carta</header>
        <main className="py-12"> {children}</main>
        <footer className="text-center leading-[60px] opacity-80 ">
          With ✨ by Sofi
        </footer>
      </body>
    </html>
  );
}
